[tox]
envlist=py310, py311, py312, py313, flake8

[testenv:py310]
basepython = python3.10

[testenv:py311]
basepython = python3.11

[testenv:py312]
basepython = python3.12

[testenv:py313]
basepython = python3.13

[testenv]
commands=py.test --cov ecs_deploy {posargs}
deps=
    pytest
    pytest-cov
    pytest-mock
    mock
    requests
    boto3
    freezegun

[testenv:flake8]
basepython = python3.13
deps =
    flake8
commands =
    flake8 ecs_deploy tests --max-line-length=140
