name: "Build"
defaults:
  run:
    shell: bash
env:
  DOCKER_REGISTRY: hazeldeploy
  DOCKER_IMAGE_NAME: ecs-deploy

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - name: Check Out Repo
            uses: actions/checkout@v2

          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1

          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              context: ./
              file: ./Dockerfile
              push: true
              tags: hazeldeploy/ecs-deploy:latest

          - name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }} > digest.txt

          - uses: actions/upload-artifact@v1
            with:
              name: digest
              path: ./digest.txt
          - name: Release
            uses: softprops/action-gh-release@v1
            with:
              files: digest.txt
              tag_name: ecs-deploy@${{ steps.docker_build.outputs.digest }}
