name: Docker Hub

on:
  push:
    branches:
      - 'develop'
      - 'master'
    tags: 
      - '*.*.*'
    
jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      -
        name: Checkout 
        uses: actions/checkout@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: fabfuel
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fabfuel/ecs-deploy:${{ github.ref_name }}
      -
        name: "Build and push (tag: latest)"
        if: github.ref == 'refs/heads/develop'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: fabfuel/ecs-deploy:latest
