name: Release

on:
  push:
    branches: [ 'feature/pypi' ]
    tags: [ '**' ]


jobs:
  pypi:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install build twine
      - name: Build
        run: python -m build
      - name: Upload to PyPI
        run: twine upload dist/*
